### ISSUE TITLE
Missing decimal in ethereum price

### ISSUE THREAD

**Issue by ansermino** [ChainSafeSystems/WeiPay#137]
On the holdings page I am seeing what I believe is a decimal issue with the price of ethereum.

Screenshot: 
![screenshot_20180826-160204](https://user-images.githubusercontent.com/14164624/44636774-8909ea00-a97b-11e8-8b75-f8462c385e72.jpg)

**Comment by masterrom** [comment]
This bug has been resolved. Balance is now being displayed with 18 decimals
