### ISSUE TITLE
Cut off text

### ISSUE THREAD

**Issue by ansermino** [ChainSafeSystems/WeiPay#138]
The text on the Activity page has text that is cut off in places. Running Android 8.0.0 on a OnePlus3.

Also see #139 re: the data that is being displayed.

![screenshot_20180826-160256](https://user-images.githubusercontent.com/14164624/44636829-bfe00000-a97b-11e8-938d-71c47881c6f8.jpg)

**Comment by CFDevelopment** [comment]
issue resolved
