### ISSUE TITLE
Wallet Usability 

### ISSUE THREAD

**Issue by CFDevelopment** [ChainSafeSystems/WeiPay#171]
**Is your feature request related to a problem? Please describe.**
Research has gone into the UX of mobile wallets and their research suggests that user's do not need to confirm their passphrase upon creating a wallet. It is assumed that there is not yet value in your wallet and a user is most likely going to use this feature once they start adding value in their wallet and there fore a stronger need to record their passphrase. 

**Describe the solution you'd like**
The confirm passphrase functionality needs to be removed from the wallet and displaced to the recover passphrase page. We will need to add password functionality with local storage so we can encrypt this private data. After either creating a wallet or recovering a wallet you must add a new field for a password that encrypts your wallet. Whenever a user wants to show their private key or passphrase they must decrypt this keystore.

**Comment by GregTheGreek** [comment]
Closing in favour fo #182
